title: "ScannerVision Docs"
email: "info@scannervision.com"
description: >- # this means to ignore newlines until "baseurl:"
 this is the documentation site of scannervision 
  you can find all the details about our products in this site


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

feedback: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

markdown: kramdown
highlighter: pygments
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]


tag_color: primary # danger, success, warning, primary, info, secondary
accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false
logo_pixels: 34
color: "#white"

stroke_color: "blue"

# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"

languages: ["en","es","it"]
default_locale_in_subfolder: true

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
collections:
  docs:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
